### PR TITLE
Add go forward and back actions

### PR DESCRIPTION
**Pull request by drunlin**

### CODE REVIEW

**Comment by flyingrub** [comment]
@mpiannucci Here is an example on how to trigger keyboard commands :)

**Comment by mpiannucci** [comment]
This is what I needed thanks!!! Will look over the merge this afternoon

**Comment by mpiannucci** [comment]
@drunlin I may take what you've done and extend it to the GUI to allow any key commands so its customizable... are you alright with that?

**Comment by mpiannucci** [comment]
Started here https://github.com/mpiannucci/gnome-shell-extended-gestures/tree/custom_keybindings

**Comment by drunlin** [comment]
@mpiannucci I am happy to do that.

**Comment by mpiannucci** [comment]
That would be awesome to get your help

**Comment by manacim** [comment]
@drunlin I copied and pasted the contents from [here](https://github.com/mpiannucci/gnome-shell-extended-gestures/pull/55/commits/3762091b3de5753bc173f4cc1a64f305cd544b9b) to their respective files but the Go Back/Forward defaults to Toggle Overview.

**Comment by drunlin** [comment]
@manacim Doesn't work? It works by sending keyboard input `Alt + Left / Alt + Right`. You can install it manually. 
https://github.com/drunlin/gnome-shell-extended-gestures#Manually

**Comment by rmader** [comment]
This works really nice here, would love to see this (or an extended version) merged and released :)

**Comment by rmader** [comment]
I've been using this for a week now and it is such a improvement for my daily work that I'd really love to see (and help) bring this forward.
I personally would say that even without generalisation this could well get merged as is (maybe with a follow up which makes the go-back and go-forward action the default for left/right swipes). But if we want to generalize it, maybe we can copy the way how the control center handles keyboard short-cuts.
Then people could even chain up gestures to keyboard short-cuts which again can do everything else.

**Comment by mpiannucci** [comment]
Sounds good... the people have spoken so I just merged it into master. Someday I will generalize it but for now this will do. 

Thanks for your work @drunlin

**Pull request merged**
