### PR TITLE
WIP: Improved app cycling

### PR DESCRIPTION
**Pull request by rmader**
This implement reversed app cycling. But there is a funny problem: switch app already was reversed (compared to how the apps appear in the alt-tap popup).
The reason for that was probably, that each switch changes the order of windows so that the previous app comes back in line. That's what happens when you hit alt-tab twice: you will get back to where you started. That's what happens atm with this PR :)

So now I'm thinking on how to make this more usable. Two options came to my mind:
 - we could you make the inverse behavior a new option (the current approach of hard-coding direction is not very user friendly anyways).
 - we spawn the alt-tab popup and have a time threshold during which we act like alt-tab if you hold alt and tab multiple times. I think that would be a nice direction, because then you could also better see which app comes next. This would make it feasible to really go in both directions without changing the window order in between.

@mpiannucci what do you think?

**Edit**: for the moment, made a new option for "last application". Because I quite like it actually :)

---
Requires #52 
Implements #48

### CODE REVIEW

**Comment by mpiannucci** [comment]
Wow this is cool! I am really a fan of last application on the beginning of the swipe sequence. That way it acts just like Alt tab. I do like the alt tab popup showing as an option too.. although Im not sure what the best "default" idea is for that option

**Comment by UladzimirKapylou** [comment]
Just as an idea: what if just to allow a user to assign any keyboard shortcut to a gesture? Then they can assign `Alt+Tab` or `Alt+Shift+Tab` or whatever.
I also think, that this could be useful when I want to add "Back" functionality in a web browser for example.

**Comment by mpiannucci** [comment]
@UladzimirKapylou please see here https://github.com/mpiannucci/gnome-shell-extended-gestures/issues/11

Back and forward functionality is merged into the master branch already as of a week or two ago! See here for that!! https://github.com/mpiannucci/gnome-shell-extended-gestures/pull/55

**Comment by rmader** [comment]
Not gonna work on this soon, closing for now

**Pull request closed without merging**
