### PR TITLE
Improved gesture direction resolution

### PR DESCRIPTION
**Pull request by hyperair**
Here's a PR that does two things:
 - Fixes handling of upward swipe for application switching (previously both upward and downward swipes changed applications in the same direction)
 - Improves the recognition of the swipe direction if the swipe is slightly diagonal

### CODE REVIEW

**Comment by mpiannucci** [comment]
Awesome!! Thank you so much... merged!

**Comment by mpiannucci** [comment]
Did you test this on 3.26? It seems to crash with an invalid property error for me

**Comment by mpiannucci** [comment]
JK Found and fixed the error!

**Comment by hyperair** [comment]
Odd, I was using 3.26.1 and didn't have any issues.

Btw, wouldn't it have made more sense to add `-2` and `-1` to `DIRECTION_LOOKUP` instead?

**Comment by mpiannucci** [comment]
Yeah this was just a testing fix to see what was actually happening. 

-2 wasn’t in the lookup table so it was causing a crash

**Comment by mpiannucci** [comment]
Actually the answer is that javascript dictionary keys cannot begin with a negative sign. So for now We are stuck converting to the positive value.

**Comment by hyperair** [comment]
Oh yeah, now that you mention it, it doesn't work in chrome inspector. Weird that I had no errors in gnome-shell for this though..

**Comment by mpiannucci** [comment]
Yeah that is weird, it definitely crashed in gnome shell for me, giving an invalid property error in the log.

**Pull request merged**
